ALTER TABLE "payment_transactions" ADD COLUMN IF NOT EXISTS "metadata" JSONB;
ALTER TABLE "api_incidents" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "api_incidents" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
