ALTER TYPE "RentalStatus" ADD VALUE IF NOT EXISTS 'DEPOSIT_PAID';
ALTER TYPE "RentalStatus" ADD VALUE IF NOT EXISTS 'DEPOSIT_FORFEITED';
ALTER TABLE "rental_orders"
  ADD COLUMN IF NOT EXISTS "start_date" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "payment_due_at" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "deposit_amount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "deposit_percent" INTEGER NOT NULL DEFAULT 20;
ALTER TABLE "rental_orders" ALTER COLUMN "deposit_percent" SET DEFAULT 10;
