"use client";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { api, money, Product } from "@/lib/api";
import { PaymentMethod, PaymentMethodSelect } from "@/components/payment-method-select";

const durations = [{ value: 1, label: "1 tháng", note: "Linh hoạt" }, { value: 3, label: "3 tháng", note: "Phổ biến" }, { value: 12, label: "12 tháng", note: "Dài hạn" }];
export function RentalForm({ products }: { products: Product[] }) {
  const search = useSearchParams(); const [items, setItems] = useState(products); const [productId, setProductId] = useState(search.get("product") || products[0]?.id || ""); const [quantity, setQuantity] = useState(1); const [duration, setDuration] = useState(1); const [startDate, setStartDate] = useState(() => { const d = new Date(); d.setDate(d.getDate() + 1); return d.toISOString().slice(0, 10); }); const [address, setAddress] = useState("123 Nguyễn Huệ, Quận 1, TP.HCM"); const [agree, setAgree] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>("payos_demo");
  useEffect(() => { void api<Product[]>("/products", { cache: "no-store" }).then((r) => { const list = r.filter((p) => p.type !== "COMPONENT" && p.productType !== "LINH_KIEN" && p.productType !== "THIET_BI_BAN" && p.priceRentMonth > 0); setItems(list); setProductId((v) => v || list[0]?.id || ""); }).catch(() => undefined); }, []);
  const product = items.find((p) => p.id === productId) || items[0]; const safeQuantity = product ? Math.min(quantity, Math.max(product.stock, 1)) : quantity; const breakdown = useMemo(() => { if (!product) return { deposit: 0, total: 0 }; const total = product.priceRentMonth * duration * safeQuantity + 300000; const deposit = Math.round(total * 0.1); return { deposit, total }; }, [product, duration, safeQuantity]);
  async function submit() { if (!product || !agree || !address.trim()) return; setError(""); setLoading(true); try { const result = await api<{ payment_demo_url: string }>("/rentals", { method: "POST", body: JSON.stringify({ product_id: product.id, type: "rent", duration, quantity: safeQuantity, start_date: startDate, shipping_address: { address: address.trim() }, agree_damage_terms: agree, payment_method: paymentMethod }) }); if (!result.payment_demo_url) throw new Error("Không nhận được liên kết thanh toán."); window.location.assign(result.payment_demo_url); } catch (e) { setError(e instanceof Error ? e.message : "Không thể tạo đơn thuê."); setLoading(false); } }
  if (!items.length) return <section className="panel p-8 text-center">Chưa có thiết bị cho thuê</section>;
  return <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><section className="panel p-5"><h2 className="font-semibold">Cấu hình đơn thuê</h2><div className="mt-6 grid gap-6"><div><b>{product?.name}</b><p className="mt-1 text-sm text-zinc-500">{product && `${money(product.priceRentMonth)}/tháng · còn ${product.stock} thiết bị`}</p></div><div className="grid gap-4 md:grid-cols-[180px_1fr]"><div><p className="mb-2 text-xs font-medium text-zinc-500">Số lượng</p><div className="flex h-11 items-center justify-between rounded-lg border border-emerald-200 bg-emerald-50/40 px-2"><button type="button" onClick={() => setQuantity((v) => Math.max(1, v - 1))}>−</button><b>{safeQuantity}</b><button type="button" onClick={() => setQuantity((v) => Math.min(product?.stock || 1, v + 1))}>+</button></div></div><div><p className="mb-2 text-xs font-medium text-zinc-500">Thời hạn</p><div className="grid grid-cols-3 gap-2">{durations.map((d) => <button key={d.value} type="button" onClick={() => setDuration(d.value)} className={`min-h-11 rounded-lg border px-2 py-1.5 text-left ${duration === d.value ? "border-emerald-300 bg-emerald-50 ring-1 ring-emerald-200" : "border-zinc-200"}`}><b className="block text-xs sm:text-sm">{d.label}</b><span className="text-[10px] text-zinc-500">{d.note}</span></button>)}</div></div></div><label className="grid gap-2 text-sm font-medium">Ngày bắt đầu thuê<input type="date" className="field" value={startDate} min={startDate} onChange={(e) => setStartDate(e.target.value)} /></label><textarea className="field min-h-24" value={address} onChange={(e) => setAddress(e.target.value)} placeholder="Địa chỉ lắp đặt" /><label className="flex gap-2 text-sm"><input type="checkbox" checked={agree} onChange={(e) => setAgree(e.target.checked)} /> Tôi đồng ý điều khoản bảo quản thiết bị.</label></div></section><aside className="grid gap-4"><section className="panel p-5"><PaymentMethodSelect value={paymentMethod} onChange={setPaymentMethod} /></section><section className="panel p-5"><h2 className="font-semibold">Tóm tắt đơn thuê</h2><p className="mt-3 text-sm">Cọc 10% tổng phí thuê (gồm lắp đặt): <b>{money(breakdown.deposit)}</b></p><p className="mt-2 text-sm text-zinc-500">Tổng phí thuê: <b>{money(breakdown.total)}</b></p>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}<button disabled={!product || !agree || !address.trim() || loading || !product.stock} onClick={() => void submit()} className="btn btn-primary mt-5 w-full">{loading ? "Đang tạo đơn..." : `Thanh toán cọc ${money(breakdown.deposit)} và giữ máy`}</button></section></aside></div>;
}
